### ISSUE TITLE
Install script

### ISSUE THREAD

**Issue by arroadie** [RobLoach/asdf-emsdk#5]
Hi Rob
I'm a bit confused with the installation script.
```shell
install_emsdk() {
    local install_type=$1
    local version=$2
    local install_path=$3

    "${install_path}/emsdk" install "${version}"
    "${install_path}/emsdk" activate --embedded
    source "${install_path}/emsdk_env.sh"
}
```

Is the assumption that the binaries are already available?

**Comment by RobLoach** [comment]
Thanks for checking it out! It uses the [`download` script](https://github.com/RobLoach/asdf-emsdk/blob/master/bin/download) to bring down Emscripten.

https://github.com/RobLoach/asdf-emsdk/blob/master/bin/download#L3-L11

**Comment by arroadie** [comment]
Can the download script be invoked directly? I had to manually do that step

**Comment by RobLoach** [comment]
I did notice that there were some differences in asdf versions on when/where it uses `download`. Are you on the latest?

**Comment by arroadie** [comment]
yup
$ asdf version
v0.7.8

**Comment by RobLoach** [comment]
This should be fixed now. Thanks!
